# Use a base image with JDK
FROM openjdk:11-jre-slim

# Set the working directory
WORKDIR /app

# Copy the correct jar file generated by Maven
COPY target/magic-api-0.0.1-SNAPSHOT.jar app.jar

# Expose the port the app runs on
EXPOSE 8080

# Command to run the application
CMD ["java", "-jar", "app.jar"]